#!/bin/bash

##################### Utility Functions #####################

function restart-daemon() {
    killall -q $(basename "$1")
    "$@" &
}

function number-of-connected-displays() {
    DISPLAY=:0 xrandr -q | grep ' connected' | wc -l
}

###################### Global Settings ######################

# Colors (nord theme)
# TRANSPARENT_COLOR='#00000000'
# NORD_0='#2e3440'; NORD_1='#3b4252'; NORD_2='#434c5e'; NORD_3='#4c566a'
# NORD_4='#d8dee9'; NORD_5='#e5e9f0'; NORD_6='#eceff4'; NORD_7='#8fbcbb'
# NORD_8='#88c0d0'; NORD_9='#81a1c1'; NORD_A='#5e81ac'; NORD_B='#bf616a'
# NORD_C='#d08770'; NORD_D='#ebcb8b'; NORD_E='#a3be8c'; NORD_F='#b48ead'

settings reset

settings set main_monitor eDP-1

~/.config/theme/themerc

# settings set polybar.height.base 30
# settings set polybar.height.extra 2 # voodoo hack in order to have space under underlines in polybar
# settings set polybar.color.background ${TRANSPARENT_COLOR}
# settings set polybar.color.foreground ${NORD_8}
# settings set polybar.color.primary ${NORD_8}
# settings set polybar.color.secondary ${NORD_7}
# settings set polybar.color.disabled ${NORD_7}

# settings set bspwm.border.width 2
# settings set bspwm.border.color.normal ${NORD_1}
# settings set bspwm.border.color.active ${NORD_8}
# settings set bspwm.border.color.focused ${NORD_8}

########################## General ##########################

# bind caps lock to backspace + add hebrew
setxkbmap -option caps:backspace
setxkbmap -option grp:alt_caps_toggle us,il
xmodmap -e "clear Lock"

# set key repeat rate
xset r rate 400 35

# TODO - dskmgrd should setup the desktops on its own
# setup monitors 
xrandr --output eDP-1 --auto --pos 0x0
bspc monitor eDP-1 -d 0-0_eDP-1
if [[ $(number-of-connected-displays) == 2 ]]; then 
    xrandr --output HDMI-1 --above eDP-1
    bspc monitor HDMI-1 -d 0-0_HDMI-1
fi

# set wallpaper
feh --bg-fill ~/.config/feh

########################### Bspwm ###########################

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config top_padding 0

bspc config border_width $(settings get bspwm.border.width)
bspc config window_gap 10

bspc config super mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
bspc config focus_follows_pointer false

bspc config normal_border_color $(settings get bspwm.border.color.normal)
bspc config active_border_color $(settings get bspwm.border.color.active)
bspc config focused_border_color $(settings get bspwm.border.color.focused)

########################## Daemons ##########################

# compositor (doesn't need to be restarted)
picom --experimental-backends &

# command palette daemon (starts sxhkd), see https://github.com/QazmoQwerty/palette
restart-daemon paletted

# desktops manager, see https://github.com/QazmoQwerty/dskmgr
restart-daemon dskmgrd

# notifications daemon
restart-daemon dunst

# policy kit (allows applications to ask for password)
restart-daemon /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1

# clipboard manager
restart-daemon clipmenud

# status bar
restart-daemon ~/.config/polybar/polybar