#!/bin/bash

##################### Utility Functions #####################

function restart-daemon() {
    killall -q $(basename "$1")
    "$@" &
}

function number-of-connected-displays() {
    DISPLAY=:0 xrandr -q | grep ' connected' | wc -l
}

###################### Global Settings ######################

settings reset
settings set main_monitor eDP-1

# The themerc sets all of the theme-related settings (colors, borders, etc.)
~/.config/theme/themerc

########################## General ##########################

# bind caps lock to backspace + add hebrew
setxkbmap -option caps:backspace
setxkbmap -option grp:alt_caps_toggle us,il
xmodmap -e "clear Lock"

# set key repeat rate
xset r rate 400 35

# TODO - dskmgrd should setup the desktops on its own
# setup monitors 
xrandr --output eDP-1 --auto --pos 0x0
bspc monitor eDP-1 -d 0-0_eDP-1
if [[ $(number-of-connected-displays) == 2 ]]; then 
    xrandr --output HDMI-1 --above eDP-1
    bspc monitor HDMI-1 -d 0-0_HDMI-1
fi

# set wallpaper
feh --bg-fill ~/.config/feh

########################### Bspwm ###########################

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config top_padding 0

bspc config border_width $(settings get bspwm.border.width)
bspc config window_gap 10

bspc config super mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
bspc config focus_follows_pointer false

bspc config normal_border_color $(settings get bspwm.border.color.normal)
bspc config active_border_color $(settings get bspwm.border.color.active)
bspc config focused_border_color $(settings get bspwm.border.color.focused)

########################## Daemons ##########################

# compositor (doesn't need to be restarted)
picom --experimental-backends &

# command palette daemon (starts sxhkd), see https://github.com/QazmoQwerty/palette
restart-daemon paletted

# desktops manager, see https://github.com/QazmoQwerty/dskmgr
restart-daemon dskmgrd

# notifications daemon
restart-daemon dunst

# policy kit (allows applications to ask for password)
restart-daemon /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1

# clipboard manager
restart-daemon clipmenud

# status bar
restart-daemon ~/.config/polybar/polybar