background_opacity: 0.90

font:
  normal:
    family: CaskaydiaCove Nerd Font Mono

window:
  opacity: 0.9
  padding:
    x: 15
    y: 15

# Colors (Gruvbox Material Dark Medium)
colors:
  primary:
    background: '0x282828'
    foreground: '0xdfbf8e'

  normal:
    black:   '0x665c54'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe78a4e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

  bright:
    black:   '0x928374'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe3a84e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'
 


# Copyright (c) 2017-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2017-present Sven Greb <code@svengreb.de>

# # Project:    Nord Alacritty
# # Version:    0.1.0
# # Repository: https://github.com/arcticicestudio/nord-alacritty
# # License:    MIT
# # References:
# #   https://github.com/alacritty/alacritty

# colors:
#   primary:
#     background: '#303141'
#     foreground: '#d8dee9'
#     dim_foreground: '#a5abb6'
#   cursor:
#     text: '#2e3440'
#     cursor: '#d8dee9'
#   vi_mode_cursor:
#     text: '#2e3440'
#     cursor: '#d8dee9'
#   selection:
#     text: CellForeground
#     background: '#4c566a'
#   search:
#     matches:
#       foreground: CellBackground
#       background: '#88c0d0'
#     bar:
#       background: '#434c5e'
#       foreground: '#d8dee9'
#   normal:
#     black: '#3b4252'
#     red: '#bf616a'
#     green: '#a3be8c'
#     yellow: '#ebcb8b'
#     blue: '#81a1c1'
#     magenta: '#b48ead'
#     cyan: '#88c0d0'
#     white: '#e5e9f0'
#   bright:
#     black: '#4c566a'
#     red: '#bf616a'
#     green: '#a3be8c'
#     yellow: '#ebcb8b'
#     blue: '#81a1c1'
#     magenta: '#b48ead'
#     cyan: '#8fbcbb'
#     white: '#eceff4'
#   dim:
#     black: '#373e4d'
#     red: '#94545d'
#     green: '#809575'
#     yellow: '#b29e75'
#     blue: '#68809a'
#     magenta: '#8c738c'
#     cyan: '#6d96a5'
#     white: '#aeb3bb'

# Colors (Nord)
# colors:
#   # Default colors
#   primary:
#     background: '0x303141'
#     foreground: '0xD8DEE9'

#   # Normal colors
#   normal:
#     black:   '0x3B4252'
#     red:     '0xBF616A'
#     green:   '0xA3BE8C'
#     yellow:  '0xEBCB8B'
#     blue:    '0x81A1C1'
#     magenta: '0xB48EAD'
#     cyan:    '0x88C0D0'
#     white:   '0xE5E9F0'

#   # Bright colors
#   bright:
#     black:   '0x4C566A'
#     red:     '0xBF616A'
#     green:   '0xA3BE8C'
#     yellow:  '0xEBCB8B'
#     blue:    '0x81A1C1'
#     magenta: '0xB48EAD'
#     cyan:    '0x8FBCBB'
#     white:   '0xECEFF4'

# # Colors (Ayu Dark)
# colors:
#   # Default colors
#   primary:
#     background: '0x0A0E14'
#     # background: '0x000000'
#     foreground: '0xB3B1AD'

#   # Normal colors
#   normal:
#     black:   '0x01060E'
#     red:     '0xEA6C73'
#     green:   '0x91B362'
#     yellow:  '0xF9AF4F'
#     blue:    '0x53BDFA'
#     magenta: '0xFAE994'
#     cyan:    '0x90E1C6'
#     white:   '0xC7C7C7'

#   # Bright colors
#   bright:
#     black:   '0x686868'
#     red:     '0xF07178'
#     green:   '0xC2D94C'
#     yellow:  '0xFFB454'
#     blue:    '0x59C2FF'
#     magenta: '0xFFEE99'
#     cyan:    '0x95E6CB'
#     white:   '0xFFFFFF'