#!/usr/bin/env bash
MONITOR=$(bspc query --monitors -d --names)
NODE=$(bspc query --nodes --node)
DESKTOP=$(dskmgr move $1 -v)
bspc node ${NODE} --to-desktop ${DESKTOP}_${MONITOR}
bspc node --focus $NODE